### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/account-financial-tools#157]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] account_debt_management
- [x] account_document
- [ ] account_financial_amount
- [ ] account_fix
- [ ] account_interests
- [ ] account_journal_security
- [ ] account_move_helper
- [ ] account_statement_aeroo_report
- [ ] account_statement_move_import
- [ ] account_ux
- [x] base_currency_inverse_rate

**Comment by mohamedhagag** [comment]
I just tested base_currency_inverse_rate with v12 and it's working fine without any modification - except making the module installable .

should I make a PR ?

**Comment by jjscarafia** [comment]
Yes please

**Comment by mohamedhagag** [comment]
@jjscarafia would you plz chk the PR #169

**Comment by jjscarafia** [comment]
done, thanks @mohamedhagag
