### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/account-financial-tools#204]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] account_debt_management
- [ ] account_document
- [ ] account_financial_amount
- [ ] account_interests
- [ ] account_journal_security
- [ ] account_statement_aeroo_report
- [ ] account_statement_move_import
- [ ] account_ux
- [ ] base_currency_inverse_rate

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
