### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/account-financial-tools#49]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [x] account_balance_constraint https://github.com/ingadhoc/account-financial-tools/pull/60
- [ ] account_debt_management
- [x] account_document
- [x] account_financial_amount
- [x] account_fix
- [ ] account_interests
- [x] account_journal_active
- [x] account_journal_security
- [x] account_move_chatter
- [x] account_move_helper
- [ ]  ̶a̶c̶c̶o̶u̶n̶t̶_̶n̶o̶_̶t̶r̶a̶n̶s̶l̶a̶t̶i̶o̶n̶
- [ ] account_reconciliation_menu
- [ ] account_statement_aeroo_report
- [x] account_statement_move_import
- [x] base_currency_inverse_rate
- [ ]  p̶o̶r̶t̶a̶l̶_̶a̶c̶c̶o̶u̶n̶t̶_̶d̶i̶s̶t̶r̶i̶b̶u̶t̶o̶r̶
- [ ] portal_account_document
