### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/account-financial-tools#75]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_balance_constraint
- [ ] account_debt_management
- [ ] account_document
- [ ] account_financial_amount
- [ ] account_fix
- [ ] account_interests
- [ ] account_journal_active
- [ ] account_journal_security
- [ ] account_move_chatter
- [ ] account_move_helper
- [ ] account_no_translation
- [ ] account_reconciliation_menu
- [ ] account_statement_aeroo_report
- [ ] account_statement_move_import
- [ ] base_currency_inverse_rate
- [ ] portal_account_document

**Comment by bodedra** [comment]
account_move_chatter https://github.com/ingadhoc/account-financial-tools/pull/140
